version: '3.1'

services:

  postgres:
    image: docker.io/postgis/postgis:11-3.3
    shm_size: 128m
    command: [
      "postgres",
      #"-c", "log_statement=all"
      "-c", "shared_buffers=250MB", # 25% of RAM
      "-c", "effective_cache_size=700MB", # 70% of RAM
      "-c", "work_mem=5MB", # 50% of RAM / active connections (100)
    ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: world
    ports:
      - 5432:5432
    volumes:
      - ./init/postgres/:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        limits:
          memory: 1000M

  mysql:
    image: docker.io/library/mysql:8-debian # 5.7 has memory issues running under docker
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: world
    ports:
      - 3306:3306
    volumes:
      - ./init/mysql/:/docker-entrypoint-initdb.d/
    deploy:
      resources:
        limits:
          memory: 1000M
