name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    name: Test
    strategy:
      matrix:
        scala: [ 2.12.x, 2.13.x, 3.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '8'
          java-package: jdk

      - name: Cache SBT
        uses: coursier/cache-action@v6
        with:
          extraKey: v1

      - name: Lint
        run: sbt "++${{ matrix.scala }} scalafmtCheckAll"

      - name: Compile
        run: sbt "++${{ matrix.scala }} compile"

      - name: Start Containers
        run: docker-compose up -d

      - name: Test
        run: sbt "++${{ matrix.scala }} test"

      - name: Check Doc Site
        if: ${{ startsWith(matrix.scala, '2.13.') }}
        run: sbt "++${{ matrix.scala }} docs/makeSite"
